# Generated by Django 3.1.4 on 2020-12-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0002_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
